version: '3'
services:
  redis:
    container_name: nestjs-backend-temp-redis
    image: redis
    ports:
      - 6379:6379
  mysql:
    container_name: nestjs-backend-temp-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    container_name: nestjs-backend-temp-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    ports:
      - 3000:3000
